### ISSUE TITLE
Documentation and Deployment steps not available

### ISSUE THREAD

**Issue by bchamnarnkit** [OfficeDev/microsoft-teams-apps-coworker-appreciation#6]
Hi Team,

I have a customer who has deployed the SHoutouts / Co-Worker appreciation app template to their tenant and have some questions. However, when I come back to check the documentation / deployment steps, it is no longer available? Is it possible to have the documentation revisited and updated for CoWorker appreciation? Thanks

**Comment by v-royavinash** [comment]
Hi @bchamnarnkit 

Please find the [link for the Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-coworker-appreciation/wiki/Deployment-Guide).
